# Generated by Django 2.2.1 on 2019-06-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleries',
            old_name='auhtor',
            new_name='author',
        ),
    ]
