# Generated by Django 2.2.1 on 2019-06-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20190601_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleries',
            name='dirname',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
