# Generated by Django 2.2.1 on 2019-06-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_galleries_dirname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleries',
            name='gitrepo',
        ),
    ]
